---
title: "Sample Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    horizontal_layout: fill
    logo: C:\\Users\\ste11\\Documents\\R fun\\R-Portfolio\\Logo 7R.PNG
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(gapminder)
library(vapoRwave)
library(magick)
library(ggthemr)
library(ggridges)
library(DT)
```

Row {data-height=750}
-----------------------------------------------------------------------

### Sample Regression Plot

```{r, warning = F, message=F, fig.width = 20, fig.height = 6}
set.seed(300)
n <- 200  # number of observations
x1 <- rnorm(n, 25, 15) # random data generated by a normal distribution
x2 <- sample(c(1,2,3), n, replace = T)
x3 <- rnorm(n, 15, 6)

beta0 <-10
beta1 <-5
beta2 <-3
beta3 <- 12
sigma <- 2

errors <- rnorm(n, 0, sigma)

Y <- beta0 + beta1*x1 + beta2*x2 + beta3*x3 + errors
  
rgrssn.data <- tibble(X1 = x1, X2 = x2, X3 = x3, Y = Y) 

rgrssn.plot <- rgrssn.data %>%
  ggplot()+
  geom_point(aes(x = X1, y = Y, color = as.factor(X2), size = X3)) +
  geom_smooth(aes(x= X1, y = Y),method = "lm", formula = y~x)+
  labs(x = "Data X1", y = "Data Y", size ="Data X3", color = "Group (X2)")+
  theme_minimal()+
  scale_color_jazzCup()

rgrssn.plot

```




Row {data-height=350}
----------------------------------------------------------------------


### Sample Density

```{r, fig.width= 10, fig.height = 4 }
rgrssn.data %>%
  ggplot()+
  geom_density_ridges(aes(x = X1, y = X2, fill = as.factor(X2)), color = NA, alpha = 0.2)+
  labs(x = "Data X1", y = "Group (X2)", fill = "Group")+
  theme_minimal()+
  scale_fill_jazzCup()

```

### Data Table

```{r, fig.width=10, fig.height=4}
datatable(rgrssn.data)
```


